version: '3'

services: 
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/code
        ports:
            - "8007:8000"
        depends_on:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3.7
